skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_amm = "CNKWbEdckorAEQJVoDnC5HNLgsqGsotqMnCbV9h4jVne"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
